# Generated by Django 4.2.1 on 2023-05-27 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=10000, null=True)),
                ('author', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
                ('main_image', models.URLField(max_length=5000)),
                ('excerpt', models.TextField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
