# Generated by Django 4.2.1 on 2023-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='urlToPost',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
