# Generated by Django 4.2.1 on 2023-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='authors/images/default.png', upload_to='authors/images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='main_image',
            field=models.ImageField(default='posts/images/default.png', upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='users/images/default.png', upload_to='users/images/'),
        ),
    ]
