# Generated by Django 4.2.1 on 2023-05-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_posts_urltopost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='TopPosts',
        ),
    ]
