# Generated by Django 4.2.1 on 2023-05-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_rename_posts_topposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topposts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='topposts',
            name='slug',
        ),
    ]
