# Generated by Django 4.2.1 on 2023-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='authors/images/<django.db.models.fields.AutoField>', upload_to='authors/images/'),
        ),
    ]
