# Generated by Django 4.2.1 on 2023-05-28 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_remove_topposts_content_remove_topposts_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('main_image', models.URLField(max_length=5000)),
                ('excerpt', models.TextField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='No category available', max_length=100)),
                ('urlToPost', models.URLField(max_length=5000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='topposts',
            name='category',
            field=models.CharField(default='No category available', max_length=100),
        ),
    ]
