# Generated by Django 4.2.1 on 2023-05-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_latestposts_topposts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestposts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topposts',
            name='category',
        ),
    ]
