# Generated by Django 4.2.1 on 2023-05-30 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_alter_latestposts_excerpt_alter_topposts_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('main_image', models.URLField(max_length=5000)),
                ('excerpt', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('urlToPost', models.URLField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('main_image', models.URLField(max_length=5000)),
                ('excerpt', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('urlToPost', models.URLField(max_length=5000, null=True)),
            ],
        ),
    ]
