# Generated by Django 4.2.1 on 2023-05-24 17:40

import app_news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='authors/images/default.png', null=True, upload_to=app_news.models.author_image_path),
        ),
    ]
