# Generated by Django 4.2.1 on 2023-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_emaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(default='No category available', max_length=100),
        ),
        migrations.AddField(
            model_name='latestposts',
            name='category',
            field=models.CharField(default='No category available', max_length=100),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(default='No category available', max_length=100),
        ),
        migrations.AddField(
            model_name='topposts',
            name='category',
            field=models.CharField(default='No category available', max_length=100),
        ),
    ]
