# Generated by Django 4.2.1 on 2023-06-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_alter_business_category_alter_latestposts_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='category',
        ),
    ]
