# Generated by Django 4.2.1 on 2023-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_remove_business_category_remove_sport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(default='Business', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(default='Sport', max_length=100, null=True),
        ),
    ]
