# Generated by Django 4.2.1 on 2023-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_business_category_sport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timeToRead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='latestposts',
            name='timeToRead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='timeToRead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='timeToRead',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
