# Generated by Django 4.2.1 on 2023-06-09 20:40

import app_news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_business_timetoread_latestposts_timetoread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='AuthorImg',
            field=models.ImageField(null=True, upload_to=app_news.models.unique_filename),
        ),
        migrations.AddField(
            model_name='latestposts',
            name='AuthorImg',
            field=models.ImageField(null=True, upload_to=app_news.models.unique_filename),
        ),
        migrations.AddField(
            model_name='sport',
            name='AuthorImg',
            field=models.ImageField(null=True, upload_to=app_news.models.unique_filename),
        ),
    ]
