# Generated by Django 4.2.1 on 2023-06-10 12:55

import app_news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0015_business_authorimg_latestposts_authorimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topposts',
            name='AuthorImg',
            field=models.ImageField(null=True, upload_to=app_news.models.unique_filename),
        ),
    ]
