# Generated by Django 4.2.1 on 2023-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0016_topposts_authorimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='AuthorImg',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='latestposts',
            name='AuthorImg',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='AuthorImg',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='topposts',
            name='AuthorImg',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
