# Generated by Django 4.2.1 on 2023-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0018_alter_business_authorimg_alter_latestposts_authorimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='AuthorImg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='latestposts',
            name='AuthorImg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='AuthorImg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topposts',
            name='AuthorImg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
