# Generated by Django 4.2.1 on 2023-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0020_alter_business_authorimg_alter_latestposts_authorimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='AuthorImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='latestposts',
            name='AuthorImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport',
            name='AuthorImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topposts',
            name='AuthorImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
