# Generated by Django 4.2.1 on 2023-06-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0021_alter_business_authorimg_alter_latestposts_authorimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='AuthorImg',
        ),
        migrations.RemoveField(
            model_name='latestposts',
            name='AuthorImg',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='AuthorImg',
        ),
    ]
