# Generated by Django 4.2.1 on 2023-06-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0022_remove_business_authorimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topposts',
            name='AuthorImg',
        ),
    ]
